project:
  type: website
  output-dir: docs   # ← important for GitHub Pages

website:
  title: "Computational Biology | Python Programming Module | 2026"
  navbar:
    left:
      - href: index.qmd
        text: General Information
      - href: software.qmd
        text: Software requirements
      - href: notebooks.qmd
        text: Notebooks
      - href: resources.qmd
        text: Resources

        

      - href: index.qmd
        text: Home
        
  page-footer:
    left: "Copyright 2026, Paulo Martel"
    center: "University of Algarve"
    right: "Built with [Quarto](https://quarto.org)"
    

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    toc-location: right

editor: visual

