---
title: "Python Programming"
author: "Paulo Martel"
date: "2026-03"
---

------------------------------------------------------------------------

### General Information

Welcome to the home of the Python Programming Module of the Computational Biology Course. In this module we will learn the basics of Python Programming, and give and introduction to Python for Data Analytics and Statistical Analysis, using a variety of specialized Python packages. The module does not requires any previous programming knowledge, although this can certainly be helpful. A previous knowledge of basic concepts of statistics (descriptive statistics, distributions, simple hypothesis testing) is required, and has been provide in the Statistics module of this course. The Python and R programming languages share many common concepts and methods, and students can certainly leverage the newly acquired R skills in their Python learning. In order to facilitate the transition, an R to Python comparative table is [available](https://pjmartel.github.io/teaching)

--------------

### Teachjng Approach

This is an hands-on course, centered on the student activities with guidance from the teacher. The teaching sessions use *Colab Notebooks*, a coding environement create bv Google that requires minimal setup from the students part. The course consists of a series of Colab Notebooks that the students will go through, replicating calculations and solving simple coding challenges. Refer to the [Notebooks Page](notebooks.qmd) to see the full and general instructions on how to use.

----------

### Module Evaluation

Student performance is this module will be evaluated by means of an exam done using the on-line tutorial system at University of Algarve (moodle based). This exam will simulaneously evaluate the Statistic and the Python Programming modules. There will be both mutiple choice questions and questions were students will be asked to write a small piece of code to perform a particular task (students will be allowed to access a table with Python commands).

The PhD students enrolling this course will be subject to an additional evaluation step. After finishing the exam, they will be given a simple data analysis exercise and be requested to produce a Colab Notebook with the analysis and explanatory comments. The Notebooks so created will be shared with the teacher for evaluation.
