---
title: "Notebooks"
author: "Paulo Martel"
---

This page lists the Google Colab Notebooks used in this course. To use them, students must have an *active Google account*. By clicking on one of the links below, students will open a copy of the notebook in their browser (Chrome is recommended, but it should work in any browser). Since they are viewing a notebook created by another person (the teacher, in this case), they need to use the option **File \> Save a Copy in Drive** to create a copy of the document in their own Google Drive. After that, any edits made to the notebook will be preserved.

Once copied, the notebook needs to be activated—that is, it must be connected to a virtual machine running on the Google Cloud. In this way, students are provided with a full computing environment without the need to install any software on their computers. Keep in mind, however, that any files created on the virtual machine will be erased once the machine disconnects. Therefore, anything that needs to be kept must be either downloaded or saved to Google Drive.

To activate the notebook, click the **Connect** button in the upper-right corner.

#### List of Colab Notebooks:<br>

-   Introduction to Python Programming (for the absolute beginner)

-   Introduction to Numpy

-   Introduction to Pandas

-   Descriptive Statistics
