---
title: "Software Requirements"
author: "Paulo Martel"
---

The use of Colab Notebooks for teaching makes software requirements essentially non-existent. However, some students may want to install the Python ecosystem locally on their own machines for various reasons:

-   **Script-based workflow:** You may prefer to code from scripts directly, rather than using the cell-based philosophy of Colab notebooks. Managing complex code and data pipelines can become cumbersome in a notebook environment.

-   **Computational limitations:** The Colab environment is free, but that comes at a cost: the virtual machine running your code is very limited in resources (CPU, RAM, and disk space). For heavy computing or very complex tasks, it may be impractical or impossible to use.

-   **Package compatibility:** You may need to install packages that are incompatible with the Colab virtual machine environment or that are very difficult to set up within it.

-   **Data storage needs:** You may require live access to data repositories and need to read from or write large amounts of data, which can be constrained in the cloud-based Colab environment.

For the above reasons, you may need to install and run Python locally. Two common ways to do so are:

**1. Install Python directly from [python.org](https://www.python.org/)**

This is simple and provides you with a basic environment and an IDE (IDLE). (**IDE**: Integrated development environment - a software application, similar to Rstudio, that offers and integrated and self-contained approach to software development).

**2. Install Conda or Miniconda from [anaconda.com](https://www.anaconda.com/)**

This gives you a much more powerful environment with access to virtually thousands of packages, along with the benefit of isolated environments—greatly reducing the risk of conflicts with other software installed on your machine. Tricky packages are often much easier to install in Conda than in a bare Python environment.

### Additional Notes:

-   **Linux or Mac users:** You already have Python installed. You only need to install additional packages (such as NumPy, pandas, Matplotlib, Seaborn, or SciPy) beyond what is installed by default on these systems. It is recommended to install these packages in virtual environments to isolate different software requirements and distributions.

-   **Notebook-based workflow:** If you prefer a local installation but still want to work in a notebook-based environment similar to Colab (a common preference among data scientists), you can install Jupyter under your Python installation. This will allow you to create, save, and run Python notebooks locally. (Colab notebooks are, in fact, Jupyter notebooks with some Google-specific tweaks.)

Should you decide to pursue a local installation, the teacher can provide assistance.
